config/routes.rb
Rails.application.routes.draw do
  root "home#home"

  namespace :auth do
    get "/strava/callback", to: "sessions#create"
  end

  resource :profile, only: [:show]
  resources :activities, only: [:show, :index]
  resources :friends_activities, only: [:index]
  resources :friends, only: [:index, :show]

  get "/:does_not_exist", to: "nawwal#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/strava_activity.rb
class StravaActivity
  attr_reader :id,
              :name,
              :distance,
              :type,
              :start_date_local,
              :elapsed_time,
              :total_elevation_gain,
              :average_speed,
              :max_speed,
              :average_heartrate,
              :max_heartrate,
              :athlete_name

  def initialize(data = {}, athlete_data = {})
    @id =                   data[:id]
    @name =                 data[:name]
    @distance =             data[:distance]
    @type =                 data[:type]
    @start_date_local =     data[:start_date_local]
    @elapsed_time =         data[:elapsed_time]
    @total_elevation_gain = data[:total_elevation_gain]
    @average_speed =        data[:average_speed]
    @max_speed =            data[:max_speed]
    @average_heartrate =    data[:average_heartrate]
    @max_heartrate =        data[:max_heartrate]
  end

  def self.activities(token)
    raw_activities = StravaService.activities(token)
    raw_activities.map do |raw_activity|
      self.new(raw_activity)
    end
  end

  def self.activity(activity_id, token)
    raw_activity = StravaService.activity(activity_id, token)
    self.new(raw_activity)
  end

  def self.friends_activities(token)
    raw_activities = StravaService.friends_activities(token)
    raw_activities.map do |raw_activity|
      self.new(raw_activity)
    end
  end
end

app/models/strava_athlete.rb
class StravaAthlete
  attr_reader :biggest_ride_distance,
              :biggest_ride_distance,
              :biggest_climb_elevation_gain,
              :total_ride_distance,
              :total_ride_duration,
              :total_ride_elevation_gain,
              :total_run_distance,
              :total_run_duration,
              :total_run_elevation_gain,
              :total_swim_distance,
              :total_swim_duration

  def initialize(data = {})
    @biggest_ride_distance =        data[:biggest_ride_distance]
    @biggest_climb_elevation_gain = data[:biggest_climb_elevation_gain]
    @total_ride_distance =          data[:all_ride_totals][:distance]
    @total_ride_duration =          data[:all_ride_totals][:moving_time]
    @total_ride_elevation_gain =    data[:all_ride_totals][:elevation_gain]
    @total_run_distance =           data[:all_run_totals][:distance]
    @total_run_duration =           data[:all_run_totals][:moving_time]
    @total_run_elevation_gain =     data[:all_run_totals][:elevation_gain]
    @total_swim_distance =          data[:all_swim_totals][:distance]
    @total_swim_duration =          data[:all_swim_totals][:moving_time]
  end

  def self.stats(athlete_id, token)
    raw_stats = StravaService.stats(athlete_id, token)
    self.new(raw_stats)
  end

  def self.friends(token)
    raw_friends = StravaService.friends(token)
    raw_friends.map do |raw_friend|
      StravaFriend.new(raw_friend)
    end
  end

  def self.friend(friend_id, token)
    raw_friend = StravaService.friend(friend_id, token)
    StravaFriend.new(raw_friend)
  end
end

app/models/strava_friend.rb
class StravaFriend
  attr_reader :id,
              :username,
              :city,
              :state

  def initialize(data = {})
    @id =       data[:id]
    @username = data[:username]
    @city =     data[:city]
    @state =    data[:state]
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :uid, presence: true
  validates :uid, uniqueness: true

  def self.from_strava(athlete, token)
    where(uid: athlete[:id]).first_or_create do |new_user|
      new_user.first_name = athlete[:first_name]
      new_user.last_name =  athlete[:last_name]
      new_user.username =   athlete[:username]
      new_user.email =      athlete[:email]
      new_user.token =      token
    end
  end

  def name
    first_name.blank? ? username : first_name
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def index
    @activities = StravaActivity.activities(current_user.token)
  end

  def show
    @activity = StravaActivity.activity(activity_id, current_user.token)
  end

  private

    def activity_id
      params[:id]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_login
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  private

    def require_login
      redirect_to root_path unless current_user
    end
end

app/controllers/friends_activities_controller.rb
class FriendsActivitiesController < ApplicationController

  def index
    @activities = StravaActivity.friends_activities(current_user.token)
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  def index
    @friends = StravaAthlete.friends(current_user.token)
  end

  def show
    @friend = StravaAthlete.friend(params[:id], current_user.token)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_login, only: [:home]

  def home; end
end

app/controllers/nawwal_controller.rb
class NawwalController < ApplicationController

  def home
    @typed_url = params[:does_not_exist]
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @athlete = StravaAthlete.stats(current_user.uid, current_user.token)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def strava_auth
    <<~HEREDOC
      https://strava.com/oauth/authorize?
      client_id=#{ENV["STRAVA_CLIENT_ID"]}
      &response_type=code
      &redirect_uri=#{strava_redirect_uri}
      &scope=view_private
    HEREDOC
  end

  def in_miles(meters)
    meters ? (meters / 1609.34).round(2) : 0
  end

  def in_hours(seconds)
    seconds ? (seconds / 3600.to_f).round(2) : 0
  end

  def in_feet(meters)
    meters ? (meters * 3.28084).round(2) : 0
  end

  def display_time(time)
    DateTime.parse(time).strftime('%l:%M %p - %e %B %Y')
  end

  def in_mph(meters_per_second)
    (meters_per_second * 2.23694).round(2)
  end

  private

    def strava_redirect_uri
      "http://localhost:3000/auth/strava/callback"
    end
end

app/views/activities/index.html.erb
<div class="wrapper">
  <h1 class="text-center">My Activities</h1>

  <hr class="divider" />

  <% @activities.each do |activity| %>
    <div class="list-group">
      <%= link_to activity.name, activity_path(activity.id), class: "list-group-item" %>
      <div class="list-group">
        <div class="list-group-item">
          <p class="list-group-item-text">Distance (miles)</p>
          <h4 class="list-group-item-heading"><%= in_miles(activity.distance) %></h4>
          <p class="list-group-item-text">Activity</p>
          <h4 class="list-group-item-heading"><%= activity.type %></h4>
          <p class="list-group-item-text">Date</p>
          <h4 class="list-group-item-heading"><%= display_time(activity.start_date_local) %></h4>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/activities/show.html.erb
<div class="wrapper">
  <div class="list-group">
    <div class="list-group-item">
      <h1 class="list-group-item-heading text-center"><%= @activity.name %> on <%= display_time(@activity.start_date_local) %></h1>
    </div>
    <div class="list-group-item">
      <p class="list-group-item-text">Distance (miles)</p>
      <h3 class="list-group-item-heading"><%= in_miles(@activity.distance) %></h3>
      <p class="list-group-item-text">Duration (hours)</p>
      <h3 class="list-group-item-heading"><%= in_hours(@activity.elapsed_time) %></h3>
      <p class="list-group-item-text">Elevation Gain (feet)</p>
      <h3 class="list-group-item-heading"><%= in_feet(@activity.total_elevation_gain) %></h3>
      <p class="list-group-item-text">Average Speed (mph)</p>
      <h3 class="list-group-item-heading"><%= in_mph(@activity.average_speed) %></h3>
      <p class="list-group-item-text">Max Speed (mph)</p>
      <h3 class="list-group-item-heading"><%= in_mph(@activity.max_speed) %></h3>
      <p class="list-group-item-text">Average Heart Rate (bpm)</p>
      <h3 class="list-group-item-heading"><%= @activity.average_heartrate %></h3>
      <p class="list-group-item-text">Max Heart Rate (bpm)</p>
      <h3 class="list-group-item-heading"><%= @activity.max_heartrate %></h3>
    </div>
  </div>
</div>

app/views/friends/index.html.erb
<div class="wrapper">
  <h1 class="text-center">My Friends</h1>
  <hr class="divider" />

  <div class="list-group">
    <% @friends.each do |friend| %>
      <%= link_to friend.username, friend_path(friend.id), class: "list-group-item" %>
    <% end %>
  </div>
</div>

app/views/friends/show.html.erb
<div class="wrapper">
  <h1 class="text-center"><%= @friend.username %></h1>
  
  <hr class="divider" />
  
  <div class="list-group">
    <div class="list-group-item">
      <p class="list-group-item-text">Location: <%= @friend.city %>, <%= @friend.state %></p>
    </div>
  </div>
</div>

app/views/friends_activities/index.html.erb
<div class="wrapper">
  <h1 class="text-center">My Friends' Activities</h1>

  <hr class="divider" />

  <% @activities.each do |activity| %>
    <div class="list-group">
      <%= link_to activity.name, activity_path(activity.id), class: "list-group-item" %>
      <div class="list-group">
        <div class="list-group-item">
          <p class="list-group-item-text">Distance (miles)</p>
          <h4 class="list-group-item-heading"><%= in_miles(activity.distance) %></h4>
          <p class="list-group-item-text">Activity</p>
          <h4 class="list-group-item-heading"><%= activity.type %></h4>
          <p class="list-group-item-text">Date</p>
          <h4 class="list-group-item-heading"><%= display_time(activity.start_date_local) %></h4>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/home/home.html.erb
<div class="jumbotron">
  <h1 class="text-center">Welcome to Strava-Curious</h1>
  <%= link_to "Log in with Strava", strava_auth, class: "btn btn-orange btn-large" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StravaCurious</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Antic+Slab|Quicksand" rel="stylesheet">
    <%= favicon_link_tag "lightning_bolt.png" %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "shared/nav" %>
    <div class="container">
      <%= yield %>
    <div>
  </body>
</html>

app/views/nawwal/home.html.erb
<div class="wrapper">
  <h1 class="text-center">Not All Who Wander Are Lost</h1>
  <hr class="divider" />
  <br />
  <p class="text-center">
    Are you really looking for '/<%= @typed_url %>' ?
  </p>
  <br />
  <h4 class="text-center">
    Perhaps check out your <%= link_to "Activities", activities_path %>
  </h4>
</div>

app/views/profiles/show.html.erb
<div class="wrapper">
  <h1 class="text-center">Welcome, <%= current_user.name %>!</h1>

  <hr class="divider" />

  <div class="list-group">
    <div class="list-group-item">
      <h2 class="list-group-item-heading activity_header">Ride</h2>
    </div>
    <div class="list-group-item">
      <p class="list-group-item-text">Longest Ride (miles)</p>
      <h4 class="list-group-item-heading"><%= in_miles(@athlete.biggest_ride_distance) %></h4>
      <p class="list-group-item-text">Biggest Climb Ridden (elevation gained in feet)</p>
      <h4 class="list-group-item-heading"><%= in_feet(@athlete.biggest_climb_elevation_gain) %></h4>
    </div>
    <div class="list-group-item">
      <p class="list-group-item-text">Total Distance (miles)</p>
      <h4 class="list-group-item-heading"><%= in_miles(@athlete.total_ride_distance) %></h4>
      <p class="list-group-item-text">Total Moving Time (hours)</p>
      <h4 class="list-group-item-heading"><%= in_hours(@athlete.total_ride_duration) %></h4>
      <p class="list-group-item-text">Total Elevation Gained (feet)</p>
      <h4 class="list-group-item-heading"><%= in_feet(@athlete.total_ride_elevation_gain) %></h4>
    </div>
  </div>

  <div class="list-group">
    <div class="list-group-item">
      <h2 class="list-group-item-heading text-center activity_header">Run</h2>
    </div>
    <div class="list-group-item">
      <p class="list-group-item-text">Total Distance (miles)</p>
      <h4 class="list-group-item-heading"><%= in_miles(@athlete.total_run_distance) %></h4>
      <p class="list-group-item-text">Total Moving Time (hours)</p>
      <h4 class="list-group-item-heading"><%= in_hours(@athlete.total_run_duration) %></h4>
      <p class="list-group-item-text">Total Elevation Gained (feet)</p>
      <h4 class="list-group-item-heading"><%= in_feet(@athlete.total_run_elevation_gain) %></h4>
    </div>
  </div>

  <div class="list-group">
    <div class="list-group-item">
      <h2 class="list-group-item-heading text-right activity_header">Swim</h2>
    </div>
    <div class="list-group-item">
      <p class="list-group-item-text">Total Distance (miles)</p>
      <h4 class="list-group-item-heading"><%= in_miles(@athlete.total_swim_distance) %></h4>
      <p class="list-group-item-text">Total Duration (hours)</p>
      <h4 class="list-group-item-heading"><%= in_hours(@athlete.total_swim_duration) %></h4>
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Oh So Curious", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", profile_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Activities", activities_path %></li>
            <li><%= link_to "Friends", friends_path %></li>
            <li><%= link_to "Friends' Activities", friends_activities_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>